setRepositories(addURLs =
                  c(CRANxtras = "https://www.stats.ox.ac.uk/pub/RWin"))
install.packages("tidyverse")
library(tools)
install.packages("haven")
install.packages("haven")
library(tools)
library(tidyverse)
library(haven)
library(tidyverse)
library(haven)
library(tidyverse)
library(haven)
# Use the `read_xpt()` function to read in the data
adsl <- read_xpt("./adsl.xpt")
adlb <- read_xpt("./adlb.xpt")
library(tidyverse)
library(haven)
# Use the `read_xpt()` function to read in the data
adsl <- read_xpt("./adsl.xpt")
adlb <- read_xpt("./adlb.xpt")
adsl %>%
  head(_) %>%
  select(_)
adsl %>%
  head(_) %>%
  select(_)
adsl %>%
  head(_) %>%
  select(_)
adsl %>%
  select(_) %>%
  str()
adsl %>%
  count(_)
count_sex <- adsl %>%
  group_by(_) %>%
  count(_)
counts2 <- counts %>%
  pivot_wider(id_cols = _, names_from = _, values_from = _)
install.packages('rmarkdown')
getOption(“repos”)
getOption("repos")
options(repos = c(CRAN = "https://cran.rstudio.org"))
install.packages('rmarkdown')
options(repos = "http://cran.rstudio.com/")
install.packages('rmarkdown')
library(rmarkdown)
install.packages("rmarkdown", repos = "https://packagemanager.rstudio.com/all/latest")
install.packages("rmarkdown", repos = "https://packagemanager.rstudio.com/all/latest")
options(repos = "http://cran.rstudio.com/")
install.packages('rmarkdown')
install.packages('commonmark')
library(commonmark)
options(repos = "http://cran.rstudio.com/")
install.packages('rmarkdown')
install.packages('commonmark')
install.packages("commonmark")
install.packages('rmarkdown')
R.version
rm(list=ls())
install.packages('rmarkdown')
options(repos = "http://cran.rstudio.com/")
install.packages('rmarkdown')
library("rmarkdown")
options(repos = "http://cran.rstudio.com/")
install.packages('markdown')
#install.packages("rlistings")
#install.packages("tidyverse")
library(tidyverse)
library(knitr)
library(rmarkdown)
knit_print.data.frame=function(x,...){
  res=rmarkdown::paged_table(x)
  rmarkdown:::knit_print.data.frame(res)
}
registerS3method(
  "knit_print","data.frame", knit_print.data.frame,
  envir=asNamespace("knitr")
)
#install.packages("rlistings")
#install.packages("tidyverse")
library(tidyverse)
library(knitr)
library(rmarkdown)
knit_print.data.frame=function(x,...){
  res=rmarkdown::paged_table(x)
  rmarkdown:::knit_print.data.frame(res)
}
registerS3method(
  "knit_print","data.frame", knit_print.data.frame,
  envir=asNamespace("knitr")
)
library(formatters)
class(adae$SUBJID)
library(rlistings)
install.packages('formatters')
install.packages('tibble')
install.packages("formatters")
install.packages("tibble")
library(rlistings)
library(formatters)
library(tibble)
library(rlistings)
library (readxl)
library (tidyverse)
library (lubridate)
library (rlistings)
library (gt)
library (knitr)
library (rmarkdown)
library (pharmaRTF)
install.packages("pharmaRTF")
options(repos = "http://cran.rstudio.com/")
install.packages("pharmaRTF")
install.packages("pharmaRTF")
library (pharmaRTF)
options(repos = "http://cran.rstudio.com/")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
options(repos = "http://cran.rstudio.com/")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
install.packages("graphics")
library (pharmaRTF)
install.packages("package:graphics")
detach("package:grDevices", unload = TRUE)
detach("package:graphics", unload = TRUE)
library(grDevices)
library(graphics)
library (Tplyr)
library(dtplyr)
install.packages("Tplyr")
library (formatters)
library (readxl)
library (pharmaRTF)
library (Tplyr)
library (rmarkdown)
library (gt)
library (lubridate)
library (lubridate)
adsl<- adsk %>% mutate(ACTARM="Total")
library(formatters)
adsl<- adsk %>% mutate(ACTARM="Total")
adsl<- adsl %>% mutate(ACTARM="Total")
adsl<- adsl
options(repos = "http://cran.rstudio.com/")
install.packages("gt")
install.packages('rmarkdown')
install.packages('markdown')
install.packages('commonmark')
install.packages('formatters')
install.packages('tibble')
install.packages("pharmaRTF")
install.packages("Tplyr")
view(adsl)
view(adsl)
library(nlme)
install.packages('commonmark')
options(repos = "http://cran.rstudio.com/")
options(repos = "http://cran.rstudio.com/")
detach("package:nlme", unload = TRUE)
library(nlme)
install.packages("nlme")
install.packages("nlme")
install.packages("nlme")
library(nlme)
fm1 <- nlme(height ~ SSasymp(age, Asym, R0, lrc),
            data = Loblolly,
            fixed = Asym + R0 + lrc ~ 1,
            random = Asym ~ 1,
            start = c(Asym = 103, R0 = -8.5, lrc = -3.3))
summary(fm1)
options(repos = "http://cran.rstudio.com/")
install.packages("gt")
install.packages('rmarkdown')
install.packages('markdown')
install.packages('commonmark')
install.packages('formatters')
install.packages('tibble')
install.packages("pharmaRTF")
install.packages("Tplyr")
install.packages("nlme")
install.packages("formatters")
install.packages("readxl")
install.packages("tidyverse")
install.packages("lubridate")
install.packages("rlistings")
install.packages("gt")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("pharmaRTF")
install.packages("dplyr")
install.packages("pharmaverseadam")
install.packages("ggplot2")
install.packages("pagenum")
install.packages("ggbreak")
install.packages("lintr")
install.packages("DT")
install.packages(“magrittr”)
install.packages(“magrittr”)
install.packages (“plotly”)
install.packages("ggfortify")
install.packages("cardx")
install.packages("gtsummary")
install.packages("flextable")
install.packages (“plotly”)
install.packages (“plotly”)
install.packages(“magrittr”)
install.packages(“magrittr”)
library (formatters)
library (readxl)
library (tidyverse)
library (lubridate)
library (rlistings)
library (gt)
library (knitr)
library (rmarkdown)
library (pharmaRTF)
library (dplyr)
library(magrittr)
library(pharmaverseadam)
library(DT)
library(pagenum)
library(ggplot2)
library(ggbreak)
library(lintr)
library(plotly)
install.packages (“plotly”)
install.packages (“plotly”)
install.packages("plotly")
install.packages(“magrittr”)
install.packages("magrittr")
install.packages("magrittr")
install.packages("magrittr")
install.packages("magrittr")
install.packages("magrittr")
install.packages("magrittr")
install.packages("magrittr")
install.packages("magrittr")
library (formatters)
library (readxl)
library (tidyverse)
library (lubridate)
library (rlistings)
library (gt)
library (knitr)
library (rmarkdown)
library (pharmaRTF)
library (dplyr)
library(magrittr)
library(pharmaverseadam)
library(DT)
library(pagenum)
library(ggplot2)
library(ggbreak)
library(lintr)
library(plotly)
library(survival)
library(survminer)
install.packages("survminer")
install.packages("Matrix")
install.packages("survminer")
install.packages("Matrix")
install.packages("survminer")
library (formatters)
library (readxl)
library (tidyverse)
library (lubridate)
library (rlistings)
library (gt)
library (knitr)
library (rmarkdown)
library (pharmaRTF)
library (dplyr)
library(magrittr)
library(pharmaverseadam)
library(DT)
library(pagenum)
library(ggplot2)
library(ggbreak)
library(lintr)
library(plotly)
library(survival)
library(survminer)
install.packages("Matrix")
install.packages("survminer")
library (formatters)
library (readxl)
library (tidyverse)
library (lubridate)
library (rlistings)
library (gt)
library (knitr)
library (rmarkdown)
library (pharmaRTF)
library (dplyr)
library(magrittr)
library(pharmaverseadam)
library(DT)
library(pagenum)
library(ggplot2)
library(ggbreak)
library(lintr)
library(plotly)
library(survival)
library(survminer)
install.packages("ggpubr")
library (formatters)
library (readxl)
library (tidyverse)
library (lubridate)
library (rlistings)
library (gt)
library (knitr)
library (rmarkdown)
library (pharmaRTF)
library (dplyr)
library(magrittr)
library(pharmaverseadam)
library(DT)
library(pagenum)
library(ggplot2)
library(ggbreak)
library(lintr)
library(plotly)
library(survival)
library(survminer)
install.packages("ggpubr")
data(package::pharmaverseadam)
data(package::"pharmaverseadam")
install.packages("pharmaverseadam")
install.packages("pharmaverseadam")
data(package::"pharmaverseadam")
install.packages("pharmaverseadam")
library(pharmaverseadam)
data(package="pharmaverseadam")
data(package="pharmaverseadam")
